### Python Crashcourse
<b>Thomas Bryan Smith</b><br>
Department of Criminal Justice and Legal Studies<br>
University of Mississippi<br>

<b>Ayan-Yue Gupta</b><br>
Behave Lab<br>
Department of Social and Political Science<br>
University of Milan<br>

### Contents
1. Libraries
2. Fundamental Data Types
3. Variables
4. Numpy Arrays (Vectors)
5. Pandas Data Frames
6. Functions
7. Reading Data into Python

### 1. Libraries

In [190]:
import os
import re

In [191]:
os.getcwd()

'c:\\Users\\Tom Smith\\Documents\\GitHub\\LLMs_Embeddings_and_Networks\\notebooks'

In [192]:
os.listdir()

['1-Python_Crashcourse.ipynb',
 '2-Embeddings.ipynb',
 '3-Network_Construction.ipynb']

In [193]:
import pandas as pd
import numpy as np

In [194]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

### 2. Fundamental Data Types

There are many different types of data and variable in Python. However, there are eight of particular note. 

Four are types of individual datum: integers, floats, strings, and boolean.

Four are collections of data (resembling R's vectors): lists, tuples, sets, and dictionaries.

##### Integer (int)

In [195]:
print(1, 'is', type(1))

1 is <class 'int'>


##### Float (float)

In [196]:
print(1.1, 'is', type(1.1))

1.1 is <class 'float'>


##### String (str)

In [197]:
print('string is', type('string'))

string is <class 'str'>


When manually entering string data into Python, it is advised that you use single quotes, ' ', when entering a word, and double quotes, " ", when entering a sentence. 

In [198]:
print('Word')
print("This is what we would call a 'sentence'")

Word
This is what we would call a 'sentence'


##### Boolean (bool)

In [199]:
print(True, 'is', type(True))

True is <class 'bool'>


##### List

In [200]:
print([1, 2, 3, 4], 'is', type([1, 2, 3, 4]))

[1, 2, 3, 4] is <class 'list'>


##### Tuple

In [201]:
print((1, 2, 3, 4), 'is', type((1, 2, 3, 4)))

(1, 2, 3, 4) is <class 'tuple'>


##### Set

In [202]:
print({1, 2, 3, 4}, 'is', type({1, 2, 3, 4}))

{1, 2, 3, 4} is <class 'set'>


##### Dictionary

In [203]:
print({'One': 1, 'Two': 2, 'Three': 3, 'Four': 4}, 'is', 
      type({'One': 1, 'Two': 2, 'Three': 3, 'Four': 4}))

{'One': 1, 'Two': 2, 'Three': 3, 'Four': 4} is <class 'dict'>


### 3. Variables

Python is an object-based language where objects are referred to as 'variables'. All of the data that was printed in the previous section was lost after printing. To retain data, it must be assigned to a variable.

Assigning and printing variables simply requires the use of an equals sign, `=`.

You can then use the `print()` function to print the content of those variables. 

You can also print variables by simply entering the name of that variable, but this will only work for a single variable. If you need to print multiple variables in the same code chunk, you must use the `print()` function.

In [204]:
name = 'Tom'
age = 33
enjoys_painting = True
years_as_professor = 2.81

In [205]:
name

'Tom'

In [206]:
name
age
enjoys_painting
years_as_professor

2.81

In [207]:
print(name)
print(age)
print(enjoys_painting)
print(years_as_professor)

Tom
33
True
2.81


In [208]:
numbers = [1, 2, 3, 4]
words = ['one', 'two', 'three', 'four']

In [209]:
print(numbers)
print(words)

[1, 2, 3, 4]
['one', 'two', 'three', 'four']


Any of the fundamental data types can be assigned to a variable, but depending on that data type they will function differently. So, it is important to be fully aware of your variable classes.

This can be challenging in the case of lists, tuples, sets, and dictionaries as they can contain any combination of int, float, string, and boolean.

In [210]:
mixed_list = ["Tom", 33, True, 2.81]
print(mixed_list)

['Tom', 33, True, 2.81]


To further confuse matters: lists, tuples, sets, and dictionaries can also contain any combination of lists tuples, sets, and dictionaries.

In [211]:
dict_of_lists = {
    "list1": [1, 2, 3, 4],
    "list2": [5, 6, 7, 8]
}
print(dict_of_lists)

{'list1': [1, 2, 3, 4], 'list2': [5, 6, 7, 8]}


### 4. Numpy Arrays (Vectors)

Applying simple mathematical functions to numeric data depends on how those data are stored (i.e., what is the class of the data object).

For example, list-class variables are not intended to handle mathematical functions, and will throw an error:

In [212]:
list_variable = [1, 2, 3, 4, 5]

In [213]:
list_variable + 2

TypeError: can only concatenate list (not "int") to list

There is a workaround to this using `for` loops, but understanding how to build these for loops can be very challenging (and a waste of your time!)

In [214]:
[x + 2 for x in list_variable]

[3, 4, 5, 6, 7]

For this reason, we need to work with the numpy library's `array` class.

In [215]:
array_variable = np.array(list_variable)

In [216]:
print(array_variable + 2)
print(array_variable - 2)
print(array_variable * 2)
print(array_variable / 2)
print(array_variable ** 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


In [217]:
print(array_variable + array_variable)
print(array_variable - array_variable)
print(array_variable * array_variable)
print(array_variable / array_variable)
print(array_variable ** array_variable)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
[   1    4   27  256 3125]


Numpy arrays are the closest equivalent of the numeric vector class in R.

However, unlike R's numeric vectors, numpy arrays follow strict mathematical rules. For example, you cannot add, subtract, multiple, or divide one array by another array of a different length:

In [218]:
np.array([1, 2, 3]) + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

On a final note, while there are no matrix type variables in Python (strictly speaking), you can create matrix-like variables in numpy by feeding the `np.array()` function a multidimensional list (a list-of-lists).

In [219]:
matrix_array = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])
print(matrix_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 5. Data Frames

In another departure from R, Python has no innate data frame class. Instead, you need to rely on the `pandas` library, which we have imported under the `pd` abbreviation.

Where numpy arrays typically start out as list objects, pandas data frames typically start out as dictionary objects:

In [220]:
data = {
    'Name': ['Thomas', 'Noah', 'Vittoria'],
    'Age': [33, 22, 29],
    'Nationality': ['British', 'German', 'Italian']
    }
print(data)

{'Name': ['Thomas', 'Noah', 'Vittoria'], 'Age': [33, 22, 29], 'Nationality': ['British', 'German', 'Italian']}


In [221]:
df = pd.DataFrame(data)
print(df)

       Name  Age Nationality
0    Thomas   33     British
1      Noah   22      German
2  Vittoria   29     Italian


### 6. Indexing

As with all things Python, your approach to indexing will depend on the class of the variable you are indexing.

However, there are some rules to be aware of that apply to most or all variable classes:

Indexing starts at 0, not 1.

In [222]:
list_variable[0]

1

Positional indexing moves forward through the variable, negative indexing moves backwards through the variable.

In [223]:
print(list_variable[2])
print(list_variable[-3])

3
3


Slicing is used to extract ranges of values from the variable.

In [224]:
print(list_variable[1:3])   # Returns the 2nd [1] and 3rd [2] positions, excludes 4th [3]. 
print(list_variable[:3])    # Returns the 1st [0] through 3rd [2] positions, excludes 4th [3].
print(list_variable[::2])   # Returns the 1st [0], 3rd [2], and 5th [4] positions, skipping every second item.
print(list_variable[::-1])  # Returns a reverse of the variable.

[2, 3]
[1, 2, 3]
[1, 3, 5]
[5, 4, 3, 2, 1]


The same rules then apply to the matrix (multidimensional) numpy array we created in the previous section. However, as in R, you need to provide a row and column index:

In [225]:
print(matrix_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [226]:
print(matrix_array[1, 2])       # Second row, third column = 6
print(matrix_array[:, 1])       # Second column
print(matrix_array[:2, :2])    # First and second rows, first and second columns
print(matrix_array[1:3, 1:3])    # Second and third rows, second and third columns

6
[2 5 8]
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


Indexing pandas data frames follows the same rules, but requires the use of the `.loc` and `.iloc` attributes.
- `.loc` allows you to index by the names of the rows and columns.
- `.iloc` allows you to index by the numeric index of the rows and columns.

In [227]:
df['Name']

0      Thomas
1        Noah
2    Vittoria
Name: Name, dtype: object

In [228]:
df[['Name', 'Age']]

,Name,Age
0,Thomas,33
1,Noah,22
2,Vittoria,29


In [229]:
df.loc[0, 'Name']

'Thomas'

In [230]:
df.iloc[0, 0]

'Thomas'

Final note about indexing missingness: it is typically represented as either `None` or `nan`, and is indexed differently depending on the class.

In [231]:
print([1, 2, None, 4, None])
print([1, 2, float('nan'), 4, float('nan')])
print([1, 2, np.nan, 4, np.nan])

[1, 2, None, 4, None]
[1, 2, nan, 4, nan]
[1, 2, nan, 4, nan]


In [232]:
np.isnan(np.array([1, 2, np.nan, 4, np.nan]))

array([False, False,  True, False,  True])

In [233]:
scores = np.array([1, 2, np.nan, 4, np.nan])
missing = np.isnan(scores)
print(scores[missing])      # Indexes for missing values
print(scores[~missing])     # Indexes for non-missing values

[nan nan]
[1. 2. 4.]


### 7. Functions

We have been using functions throughout this crash course.

Functions innate to Python can be called using the appropriate function call (i.e., the keyword associated with that function). For example:
- `print()`

Functions that are loaded in from external libraries (os, re, numpy, pandas, etc.) generally need to be called as a suffix of the library name or abbreviation:
- `os.getcwd()`
- `np.array()`

You can work around this by loading individual functions from a library into your environment. This will allow you to call those functions without needing to call the library explicitly:

In [234]:
from os import getcwd

In [235]:
getcwd()

'c:\\Users\\Tom Smith\\Documents\\GitHub\\LLMs_Embeddings_and_Networks\\notebooks'

Building your own custom functions is a good habit. It can ensure that you standardize your workflow. However, it can be fairly challenging without regular practice.

In [236]:
def dot_product(a, b):
    result = sum(x * y for x, y in zip(a, b))
    return result

In [237]:
dot_product([8, 4], [-5, 2])

-32

In [238]:
def cosine_similarity(a, b):
    dot_product = sum(x * y for x, y in zip(a, b))
    norm_a = sum(x ** 2 for x in a) ** 0.5
    norm_b = sum(y ** 2 for y in b) ** 0.5
    
    if not norm_a or not norm_b:
        return 0.0  # Avoid division by zero for zero vectors
        
    return dot_product / (norm_a * norm_b) 

In [239]:
cosine_similarity([8, 4], [-5, 2])

-0.6643638388299198

MIT License

Copyright (c) 2026 Thomas Bryan Smith

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.